# Generated by Django 4.0.4 on 2022-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_jewerly_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typejewerly',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='jewerly',
            name='jewerlyImage',
            field=models.ImageField(blank=True, upload_to='jewerly/%Y/%m'),
        ),
    ]
