# Generated by Django 4.0.4 on 2022-05-18 16:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_typejewerly_options_alter_jewerly_jewerlyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, region='VN'),
        ),
    ]
