# Generated by Django 4.0.4 on 2022-05-18 16:24

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_supplier_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='VN', validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$')]),
        ),
    ]
