# Generated by Django 4.0.4 on 2022-05-19 03:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_supplier_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phoneNumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{8,10}$')]),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.BooleanField()),
                ('address', models.TextField(blank=True, null=True)),
                ('phoneNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{8,10}$')])),
                ('idNumber', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{12,12')])),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/%Y/%m')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.BooleanField()),
                ('address', models.TextField(blank=True, null=True)),
                ('phoneNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{8,10}$')])),
                ('idNumber', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{12,12')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
