# Generated by Django 4.0.4 on 2022-05-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_category_remove_jewerly_typejewerly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewerly',
            name='typeJewerly',
            field=models.ManyToManyField(blank=True, null=True, related_name='typejewerly', to='api.typejewerly'),
        ),
    ]
