# Generated by Django 4.0.4 on 2022-05-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_jewerly_typejewerly'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['categoryName']},
        ),
        migrations.AlterModelOptions(
            name='typejewerly',
            options={'ordering': ['typeName']},
        ),
        migrations.AlterField(
            model_name='jewerly',
            name='typeJewerly',
            field=models.ManyToManyField(blank=True, null=True, to='api.typejewerly'),
        ),
    ]
