# Generated by Django 4.0.4 on 2022-05-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_category_options_alter_typejewerly_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
