# Generated by Django 4.0.4 on 2022-05-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customer_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewerly',
            name='typeJewerly',
        ),
    ]
