# Generated by Django 4.0.4 on 2022-05-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_jewerly_typejewerly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typejewerly',
            name='category',
        ),
    ]
