# Generated by Django 4.0.4 on 2022-05-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220521_2106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='jewerly',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='TypeJewerly',
        ),
        migrations.DeleteModel(
            name='Jewerly',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
