# Generated by Django 4.0.4 on 2022-05-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_category_remove_jewerly_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['categoryName'],
            },
        ),
        migrations.CreateModel(
            name='TypeJewerly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.category')),
            ],
            options={
                'db_table': 'typejewerly',
                'ordering': ['typeName'],
            },
        ),
    ]
