# Generated by Django 4.0.4 on 2022-05-21 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_category_typejewerly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{8,10}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
    ]
