# Generated by Django 4.0.4 on 2022-05-21 14:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewerly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewerlyName', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('jewerlyImage', models.ImageField(blank=True, upload_to='jewerly/%Y/%m')),
                ('active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.supplier')),
                ('typeJewerly', models.ManyToManyField(blank=True, null=True, to='api.typejewerly')),
            ],
        ),
    ]
