# Generated by Django 4.0.4 on 2022-05-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_category_active_supplier_active_typejewerly_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='typejewerly',
            name='typeName',
            field=models.CharField(max_length=255),
        ),
    ]
