# Generated by Django 4.0.4 on 2022-06-04 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phoneNumber',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{8,10}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplierName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
