# Generated by Django 4.0.4 on 2022-06-04 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_supplier_email_alter_supplier_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phoneNumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{8,10}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplierName',
            field=models.CharField(max_length=255),
        ),
    ]
