# Generated by Django 4.0.4 on 2022-06-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_supplier_email_alter_supplier_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewerly',
            name='jewerlyImage',
            field=models.ImageField(null=True, upload_to='jewerly/%Y/%m'),
        ),
    ]
