# Generated by Django 4.0.4 on 2022-06-11 13:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_firstname_customer_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptDate', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.employee')),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
        migrations.CreateModel(
            name='ReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unitPrice', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('jewerly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.jewerly')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.receipt')),
            ],
            options={
                'db_table': 'receiptdetail',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitPrice', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('jewerly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.jewerly')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.order')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceDate', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.employee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.order')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
