# Generated by Django 4.0.4 on 2022-06-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_order_receipt_receiptdetail_orderdetail_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
