# Generated by Django 4.0.4 on 2022-06-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_customer_active_employee_active_invoice_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptdetail',
            name='jewerly',
        ),
        migrations.RemoveField(
            model_name='receiptdetail',
            name='receipt',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='ReceiptDetail',
        ),
    ]
