# Generated by Django 4.0.4 on 2022-06-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_customer_idnumber_alter_employee_idnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
