# Generated by Django 4.0.4 on 2022-06-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerId',
            field=models.IntegerField(null=True),
        ),
    ]
