# Generated by Django 4.0.4 on 2022-06-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_order_customerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customerId',
        ),
    ]
