# Generated by Django 4.0.4 on 2022-06-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_customer_idnumber_alter_employee_idnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
