# Generated by Django 4.0.4 on 2022-06-27 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
